feat: modify husky pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,17 +1,25 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-echo '🏗️👷 Styling your project before committing👷‍♂️🏗️'
-echo 'please be patient, this may take a while...'
+echo 'Running Git Hooks'
 
-# Check ESLint Standards
-yarn lint ||
-(
-    echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
-          Run yarn lint, add changes and try commit again.';
+echo "🔎  Checking validity of types with TypeScript"
+
+yarn type-check || (
+    "⛔️  There is a type error in the code, fix it, and try commit again. ⛔️";
     false;
-)
+    )
 
-echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'
 
-npx lint-staged
+echo "✅  No TypeError found"
+echo "🔎  Running linter.."
+
+yarn lint || (
+    echo '⛔️  There is a problem in the code. Check linter, add changes and try commit again. ⛔️';
+    false;
+    )
+
+echo '✅ No Eslint error found'
+echo '⌛️ Running lint staged and git commit ⌛️'
+
+yarn lint-staged
